### PR TITLE
Hancitor build version with letters

### PR DESCRIPTION
**Pull request by voidm4p**
image

### CODE REVIEW

**Comment by doomedraven** [comment]
i would suggest to change it to `[\w\d]`i saw builds which contains \`, uppercase, `_` etc

**Comment by voidm4p** [comment]
Fixed now!

**Comment by karttoon** [comment]
Cool, thanks for the catch. The build used to be just numeric and was a date format, something like 221117 for today.

**Comment by doomedraven** [comment]
i have observed patterns like:
* 13yac11
* 03_10

few other

**Pull request merged**
